language: elixir
sudo: false

jobs:
  include:
    - &test
      elixir: 1.7.4
      otp_release: 19.3
    - <<: *test
      elixir: 1.8.2
      otp_release: 20.3
    - <<: *test
      elixir: 1.9.4
      otp_release: 21.3
    - <<: *test
      elixir: 1.10.3
      otp_release: 22.3
    - <<: *test
      elixir: 1.10.3
      otp_release: 23.0
      after_success: mix coveralls.travis

    - stage: verify
      elixir: 1.10.3
      otp_release: 23.0
      before_install: |-
        pip install --user --quiet --ignore-installed geoip2

        mkdir -p data

        pushd data
          curl -s "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN&license_key=${MAXMIND_LICENSE_KEY}&suffix=tar.gz" -o GeoLite2-ASN.tar.gz
          curl -s "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=${MAXMIND_LICENSE_KEY}&suffix=tar.gz" -o GeoLite2-City.tar.gz
          curl -s "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=${MAXMIND_LICENSE_KEY}&suffix=tar.gz" -o GeoLite2-Country.tar.gz

          tar -xzf GeoLite2-ASN.tar.gz
          tar -xzf GeoLite2-City.tar.gz
          tar -xzf GeoLite2-Country.tar.gz

          find . -name '*.mmdb' -exec mv {} . \;
        popd
      script: |-
        cd "${TRAVIS_BUILD_DIR}/verify"

        rm -f ./ip_set.txt
        . ./generate_ip_set.sh

        # verify geolix results
        pushd geolix
          mix geolix.verify
        popd

        # verify python results
        pushd python
          python verify.py
        popd

        # diff results
        diff geolix_results.txt python_results.txt

    - stage: code quality
      elixir: 1.10.3
      otp_release: 23.0
      script:
        - mix format --check-formatted
        - mix credo --strict
